### ISSUE TITLE
Infelizmente não consegui rodar o projeto

### ISSUE THREAD

**Issue by danvitoriano** [dclimaites/JavaPlataform#1]
Rapazes, infelizmente não conseguir rodar o projeto de vocês! 😢 

Ao executar o método Main, recebo a seguinte mensagem no Eclipse:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Main has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)

```

Procurem testar novamente e veja se acontece este erro com vocês. Tentem consertá-lo e publiquem as alterações no repositório.
Outra necessidade importante que vocês esqueceram:
- [ ] é preciso ter um README no projeto do Github descrevendo como devo instalar e rodar o programa, além de instruções de como criar e usar o chatbot no Telegram.

Fico no aguardo. Respondam quando estiver ok na própria Issue.

**Comment by danvitoriano** [comment]
Baixei o projeto no Linux ao invés do Mac e funcionou. Talvez alguma lib não tenha compilado corretamente, já que vocês não fizeram nenhum update no projeto.

Melhorem depois o README do projeto de vocês e vejam se acontece um problema de encoding (acentuação) no bot de vocês, quero compartilhá-lo no Twitter!
